1. Inicia tu proyecto: npm init -y
2.Instala Express:npm install express
3.Instala el cliente de PostgreSQL: npm install pg
4.Para instalar CORS en tu proyecto de Node.js y Express, usa el siguiente comando: npm install cors
5.Para manejar variables de entorno (como las credenciales de la BD).:npm install dotenv
6.Reinicia automáticamente el servidor cuando cambias el código (solo desarrollo).:npm install --save-dev nodemon
